# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27dc835e56231b0470f89daac68b6409be6e1a41b9d39bd451f0ea77e0eddb30e23abc4bb8dc3eddabffdb3d27dee7e94eb87eae0123949dcf7304de6f6948c9

test:
  secret_key_base: a427c991ba898dd1fc564b452e4976831afbb4054db8e946e9ffbe6fcdcbd21c7b6cb7f33749d32514ac677034191acd7f93eb0f4b54c05196c2d09bbca88f04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
